### PR TITLE
Update m21ToXml.py and xmlToM21.py for MuseScore 2

### PR DESCRIPTION
**Pull request by doctor-schmidt**
before

[output before.txt](https://github.com/cuthbertLab/music21/files/428727/output.before.txt)

after

[output after.txt](https://github.com/cuthbertLab/music21/files/428728/output.after.txt)

### CODE REVIEW

**Comment by doctor-schmidt** [comment]
Errors are with accidentals in 'root-alter' and 'root-base' musicxml tags
e.g
>>> accidental = int('-1.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '-1.0'
>>> accidental = int(float('-1.0'))
>>> accidental
-1

**Comment by mscuthbert** [comment]
Great patch.  One issue though: http://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-semitones.htm -- reports that 0.5 is acceptable, so we should only be converting to int if (int(alter) == float(alter)), but leave it alone in case it's not.  Could you extend this patch to do so and add a test case for that?  Thanks!

**Comment by mscuthbert** [comment]
Actually, I know what would be best -- I'm going to merge this and then I'll immediately put that in, because there are a lot of places where it would be useful.  Thanks!

**Comment by mscuthbert** [comment]
Ha!  I already had the right routine:  common.numToIntOrFloat()

**Pull request merged**
