### PR TITLE
Adding a parser for **harm spines in Humdrum data

### PR DESCRIPTION
**Pull request by napulen**
This is a PR for extending music21's humdrum parser to support `**harm` spines with Roman Numeral Analysis annotations.

What's added: 
- A `harmparser` module based on regular expressions to parse the annotations in a `**harm` spine.
- A `HarmSpine` class that follows a similar structure as `KernSpine` and `DynamSpine`
- A function within `HarmSpine` to convert the parsed `**harm` annotations into music21 `RomanNumeral` objects
- Integration of those `RomanNumeral` objects into the resulting stream out of the Humdrum input file
- Changes of key are taken into account in the `RomanNumeral` objects if they are indicated within the `**harm` spine
- The parser has been tested with all the annotations in [this dataset](https://github.com/napulen/haydn_op20_harm). All the files produce a valid music21 stream with `RomanNumeral` annotations in the proper offset.

Future work:
- Testing on [TAVERN](https://github.com/jcdevaney/TAVERN) and other sources of `**harm` data
- Alternative annotations within square brackets are ignored. For example: `iib[IV]` would be translated as `ii6` in the `RomanNumeral` object

### CODE REVIEW

**Comment by mscuthbert** [comment]
Hi Nestor -- this would be wonderful.  Note two things that will need to happen:  (1) the coverage needs to increase -- a decrease of 0.1% is a significant decrease for music21.  (2) the license and copyright needs to be the same as other music21 modules.  Thank you!

**Comment by napulen** [comment]
Thank you, Michael. Looking into it now.

- [ ] Increase coverage
- [x] Match license and copyright

License is matched now to the rest of `music21`.

Regarding the coverage, coveralls indicates that none of the code I added is being touched. My guess is that this is because none of the test files has a `**harm` spine in it. I need to add a test file that has a `**harm` spine in it and then make that file part of the tests. Hopefully that will exercise the new code.

**Comment by napulen** [comment]
Coverage is doing fine now.

**Comment by napulen** [comment]
Hi Michael. Thank you for the encouraging words! Really appreciate it.

I will break down the steps you suggested for my own organization of the commits to this PR.

Regarding the tests on roman numerals, these are the ones I can think of:
- [ ] Testing common triads
  - [ ] Each diatonic scale degree in a major/minor context
  - [ ] Neapolitan. Italian, French, and German augmented sixths
- [ ] Test seventh chords and inversions
  - [ ] Test inversions in triads
  - [ ] Test inversions in seventh chords
  - [ ] Test that the `pitches` in seventh chords (of various scale degrees) are correct
- [ ] Test that changes of key throughout the piece make it to the `RomanNumeral` objects
- [ ] Test that the `offset` of the `RomanNumeral` objects is correct

Regarding `convertHarmToRoman`, it is a static function and I have no objection to put it within the `harmparser` module. Adding that step to the list:
- [ ] Move `convertHarmToRoman` to the `harmparser` module
- [ ] Write a `docstring` for `convertHarmToRoman` that specifies input/output data types and similar information than other `music21` functions
- [ ] Write unit tests to check the conversion between `**harm` and `RomanNumeral` strings is correct. Specially things that change between notations.
  - [ ] Check that inversions are translated correctly
  - [ ] Check that `Gn`, `Fr`, and `Lt` are translated correctly
  - [ ] Check that alterations are translated correctly

Regarding durations in `**harm` annotations, I have deliberately not dealt with them for now, because it is not mentioned in the `**harm` representation whether durations can/should be written in a `**harm` spine as they are in a `**kern` spine. The data from Stanford that I've seen does **not** encode durations in `**harm` spines. However, TAVERN does. Also, I am afraid that in order to support durations in a `**harm` spine I need to either 1) Modify the HarmDefs to support that 2) Dig deeper into how you do it in the `KernSpine` class. I'd prefer to defer that conversation for the future and implement them as "durationless" events associated to a specific `offset` for now. I'd be happy to hear your opinion on this. In the meantime, I will try to find time to implement the rest of items in the list.

Thank you!

**Comment by mscuthbert** [comment]
This looks like a great list -- THANKS!

**Comment by napulen** [comment]
I tried to compress all the items on the first list into a few unit tests. 
- Now there are three unit tests instead of one
- Two custom-made humdrum files for testing the syntax. All triads in both modes. All diatonic sevenths in both modes. One instance of Neapolitan, Italian, French, and German subdominants.

**Comment by napulen** [comment]
Ok. I think it's ready for another check!

**Comment by mscuthbert** [comment]
Thanks! sorry i missed this -- will review this weekend, or ping me again if you don't hear from me -- sorry to neglect this.

**Comment by napulen** [comment]
No problem! Thank you for the reply!

**Comment by mscuthbert** [comment]
This is FANTASTIC!!!! THANK YOU!

**Comment by mscuthbert** [comment]
Amazing tests!

**Comment by napulen** [comment]
Glad to contribute. Thanks!

**Pull request merged**
