### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by doctor-schmidt**
Pull request for the first 10 bach chorales (repeats and lyrics added)
bwv267.xml may be removed, as I don't know how to delete or rename files in GitHub

### CODE REVIEW

**Comment by mscuthbert** [comment]
I see it's closed -- do you still want it reviewed?

**Comment by doctor-schmidt** [comment]
Deleted by accident. Github newbie me!

**Comment by mscuthbert** [comment]
whoops -- apparently it can't be reopened because it wasn't connected to a repertory.  Once I get v.5 released next week, let's start adding these again for v5.2 immediately.

**Comment by doctor-schmidt** [comment]
I’ll start doing pull requests, 5 chorales at a time.
Here are my rules:
- add only the first verse of text for now (plus repeats and fermatas).
- keep original notes, key signatures and occasional instrumental parts identical.
- use only bwv numbering to make overwriting easy.
- credit Margueret Greentree with great pleasure!

Have a nice day!

Norman

**Pull request closed without merging**
