### PR TITLE
Replace spanned elements when stripping ties

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
Spanners would disappear if a terminus was stripped by `stripTies`:

```
sch = corpus.parse('schoenberg/opus19', 6)
sch.stripTies().measure(8).show()
```

Before:

stripped-no-spanner

After:

stripped-with-spanner

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
Now that I know more about `coreElementsChanged` I noticed that this could have been removed during my first patch for stripTies last summer because using `stream.remove()` instead of `pop()` obviates the need.

**Comment by mscuthbert** [comment]
hmmm.... I'll have to think on this -- sometimes we call stripTies in order to do musical analysis but then want to show the original score (for instance, with all "complex" notes turned orange, or with a pitchClass analysis in the lyrics).  Will this change mean that the spanners disappear in the original score if it is shown?  It might be that we need to make a copy of the spanner and put that copy into the stripTies score.  Thoughts?

**Comment by jacobtylerwalls** [comment]
This acts on the return object only, so if it's inPlace every transformation is destructive, and if not, then we're only acting on the copy. In your example are you thinking of an inPlace=False operation?

**Comment by mscuthbert** [comment]
Ah! Of course -- you're right, we make a deepcopy so everything is new in the new output, and if we're doing inPlace=True then it's much less of a problem that the original notes no longer are part of spanners.

<s>It does make me think that there's a bigger (and pre-existing) bug on cleaning-up sites (isDead=True) in that notes that are removed still think they're in spanners.</s> Nope!  Checked the code -- replaceSpannedElements calls .replace which ensures that sites are cleaned up properly.  Okay -- looks good (and thanks for the timer test!) -- merging!

**Pull request merged**
