### PR TITLE
Set literal name parsed from SEQUENCE_TRACK_NAME or INSTRUMENT_NAME on instrument.partName or .instrumentName

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
Refs #684 

**Before**: `instrument.partName` was not set on instruments created from parsing MIDI. If the instruments could successfully be normalized to m21 instruments, `.partName` on the `Part` would come out okay because of the way the property drills down to the instrument types. If a default instrument was created from a string like "Marcato" that doesn't normalize, the information was lost (there was no specific instrument for the property to drill down to).

**Now**: We store the text from SEQUENCE_TRACK_NAME or INSTRUMENT_NAME meta messages on `instrument.partName` so it will flow upstream to `Part.partName` and thus to an xml export, whether the text successfully normalizes to a specific instrument or not.

### CODE REVIEW

**Comment by mscuthbert** [comment]
will think about whether we want to override the PartName if an instrument can be detected from the MIDI program number -- a lot of MIDI files give good program numbers but just 'Instrument' or blank spaces for instrument name.  Perhaps checking for these two (putting a .strip() on decoded) and only setting part name if not matching either of these?  Otherwise looks great!

**Comment by jacobtylerwalls** [comment]
I think this should come out okay with no add'l changes because .partName skips the generic Instrument with no details (track name) when returning the name of the first normalized instrument (program change). Will add a test👌🏻

**Comment by jacobtylerwalls** [comment]
Oh now I see it, setting partName on that generic instrument (spaces etc) will introduce a problem -- you're right. Checking for spaces is simple. What about post processing to remove the generic instrument object if two are found at offset 0? (Thinking of this very test case with the instrument "Inst 1".)

**Comment by jacobtylerwalls** [comment]
Now I'm thinking to handle each message separately, if TRACK_NAME set partName (even if spaces?); if INSTRUMENT_NAME set instrumentName, but only if not spaces. Still have the scenario where Inst 1 INSTRUMENT_NAME coincides with Guitar PROGRAM_CHANGE.

**Comment by mscuthbert** [comment]
THANK YOU!  This is wonderful!

**Pull request merged**
