### PR TITLE
A few ChordSymbol fixes

### PR DESCRIPTION
**Pull request by gregchapman-dev**
(was 'Bbpedal', should be 'B-pedal')

### CODE REVIEW

**Comment by gregchapman-dev** [comment]
I did modify one test to actually test that the new code did the right thing.  But it's on the same line as before, which was already tested, so no coverage change.

**Comment by gregchapman-dev** [comment]
Added another fix: CHORD_TYPES['Neapolitan'] had '1,2-,3,5-' but should be '1,-2,3,-5'.

**Comment by gregchapman-dev** [comment]
Third fix: when applying ChordSymbol modifications, if a modification is an 'alter' for a degree not in the ChordSymbol, turn it into an 'add' instead (and apply it).

**Comment by mscuthbert** [comment]
Ah, this was leftover from an early version of ChordSymbol where b was used instead of -.  Just fixed a doc that also referenced the old way.  Will merge when tests pass.

**Pull request merged**
