### PR TITLE
Text added bwv275

### PR DESCRIPTION
**Pull request by doctor-schmidt**

### CODE REVIEW

**Comment by mscuthbert** [comment]
thank you!

**Comment by doctor-schmidt** [comment]
finally getting my head wrapped around Github, thanks for your patience!

**Comment by mscuthbert** [comment]
Oh thank you!  It's so wonderful to be getting these requests, and it's super easy for me to verify and merge them!

**Comment by mscuthbert** [comment]
I have some older requests to integrate other changes from you -- let me get a minute to try to find them and make sure that they're in the system.

**Comment by doctor-schmidt** [comment]
If you want we can go from the current state. I can update 1 by 1. Then In a year ( 365 pull requests later )
everything will be up to date with comments reflecting changes, (+ solid green contribution graph for me :-)

The older requests mostly only changed:   ‘ (apostrophe)  ->  ’  (right single quotation),  ss  ->  ß (eszett)
and Margaret Greentreeused by permission  ->  Margaret Greentree - used by permission
If we go from here it will be obvious which chorale has been modified.

Have a nice weekend!
Norman

**Comment by doctor-schmidt** [comment]
Don’t look for them, here they are with most recent changes.


I just did a pull request that will update all 352  corpus/bach/bwvxxx.mxl files (required 4 commits).
Might save you some time. And once merged I won’t have to use my local corpus anymore!

**Pull request merged**
