### PR TITLE
Updates to feature extractors to match jSymbolic implementation

### PR DESCRIPTION
**Pull request by mjwalter**
The current music21 feature extractors "normalize" by dividing by the maximum element in an array. This keeps all values <= 1, but is not what normalization is (and is not how jSymbolic implements it). Rather, the *sum* of all values in the array should be 1.

"Most Common Pitch" and "Fifths Pitch Histogram" each had a specific difference in implementation from jSymbolic; these have also been corrected.

This pull request would address issue #273.

### CODE REVIEW

**Comment by mscuthbert** [comment]
aha! I thought we were following JSymbolic's methods -- if they don't do the normalization of setting the largest to 1 then there's no reason we should either.  Will watch the build and then commit if it passes.  If it doesn't, feel free to reuse the method "normalize" to do the new thing -- in fact that would be better, so that if anyone has written an extractor that calls "normalize" it will still work, just with the new normalization scheme.

**Comment by mjwalter** [comment]
Note that my updated test suites referred to the features as extracted by jSymbolic (and not just the result of my new code).

**Comment by mjwalter** [comment]
I missed a couple test cases elsewhere in the project to update – will continue to work on this until it passes.

**Comment by mscuthbert** [comment]
Thanks!

It's possible that bwv66.6 might at some point trigger a change of meter problem as Norman is updating the chorales and putting in repeats, so we can fix that to another file at that time.

**Pull request merged**
