### PR TITLE
Issue 14 hotfix

### PR DESCRIPTION
**Pull request by johnMamish**
Fixes the most urgent needs for issue 14.  Namely, getting the composer and title from humdrum metadata.  All the parsing machinery was there, it looks like a little bit of plumbing was just missing.

The titles still require HTML unescaping.  For instance, `Herr Jesu Christ, ich weiß gar wohl` will be entered into metadata as `Herr Jesu Christ, ich wei&szlig; gar wohl`.

Naive attempts to resolve this remaining issue resulted in the Lilypond parser crashing when I run `.show()` on the title containing the ß.

### CODE REVIEW

**Comment by johnMamish** [comment]
Hmm... it appears that the CI tests do not expect the humdrum files to have any metadata.  That is where my tests are failing.

```
Expected:
    {0.0} <music21.stream.Part spine_0>
    ......

Got:
    {0.0} <music21.metadata.Metadata object at 0x7f8c34e19b10>
    {0.0} <music21.stream.Part spine_0>
    .....
```

Suggestions?

**Comment by mscuthbert** [comment]
I imagine that with your change, the authoritative answer to some tests will have changed too. It seems to make sense that there will now be a metadata object there so you can probably update the tests to expect a metadata object before the first Part

**Comment by johnMamish** [comment]
I need to put this on the backburner for a little bit.

**Comment by mscuthbert** [comment]
Fixed using some of your code but a slightly different approach.  Thank you!

**Pull request closed without merging**
