### PR TITLE
Add StreamPlayer2 to master

### PR DESCRIPTION
**Pull request by jbigdata-git**
Hi,

Based on _pyGame_ **StreamPlayer** api don't manage _soundfont_.
To achieve the addon [music21drums](http://github.com/jbigdata-git/music21drums) _soundfont_ managing is required, that's why I dev **StreamPlayer2** class.
It's a kind of _StreamPlayer_ V2, full based on _fluidsynth_, no more _pyGame_. 
The tuto snippet is:
> player = StreamPlayer2(driver='alsa', soundfont='../_soundfont/PNS_Drum_Kit.SF2')
> player.setMidiFile('../_midi/tuto_drumsnotes.mid')
> player.play()
> player.stop()

StreamPlayer2 added values are : 
-  _StreamPlayer_ api like: simple and easy to use.
-  _soundfont_ managing in python dev.
-  _fluidsynth_ features embeded via _pyFluidSynth_ package.

Devs are [here](http://github.com/jbigdata-git/music21drums/tree/main/music21drums), test cases in _player.py_.

JB.

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
Hi @jbigdata-git , if you have changes to propose please make sure you choose a branch from your fork of music21 when opening a pull request. This pull request is between two branches of this repository.

**Comment by mscuthbert** [comment]
We are also highly unlikely to take a PR that requires fluidsynth as a package until it can be installed in all major OSes via requirements.txt or `pip install fluidsynth` or the like.  Demos that require external modules have been removed from the music21 repo to music21-tools over time.  (for instance, Gregorio, etc.) and even Lilypond was scheduled for removal until they made a MacOS-64bit binary easily installed.

**Comment by jbigdata-git** [comment]
Thank you for the explanation.
Initially, I wanted to use the post [music21 Lessons] to share the result of my experience using music21 in playing embedded drum scores in Music21 on Linux.
From all my discussions over the years on IT across many communities, this is the first time that I see MacOS as a prerequisite for development. It is probably related to the fact that it is in the artistic field.
It reminds me that in the last century the first C programs with Windows were on Mac, the box with the 1 button mouse, it worked wonderfully without bug...

**Comment by jacobtylerwalls** [comment]
If the primary motivation is to export unpitched notes to musicxml and MIDI, it's on the roadmap for v7 -- we already have the musicxml part worked out. If you want to help you could try out the `unpitched` branch and contribute some tests or look for bugs. Cheers.

**Pull request closed without merging**
