### PR TITLE
Fix posix path metadata bundles

### PR DESCRIPTION
**Pull request by mscuthbert**

### CODE REVIEW

**Comment by sebaspm24** [comment]
I tried it but still dont work. Do you know what can I do?

`bachBundle = corpus.search('bach', 'composer')
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\music21\metadata\bundles.py", line 1147, in read
    newMdb = pickle.loads(uncompressed)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1013, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<pyshell#51>", line 1, in <module>
    bachBundle = corpus.search('bach', 'composer')
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\music21\corpus\manager.py", line 265, in search
    readAllMetadataBundlesFromDisk()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\music21\corpus\manager.py", line 330, in readAllMetadataBundlesFromDisk
    cacheMetadataBundleFromDisk(corpusObject)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\music21\corpus\manager.py", line 320, in cacheMetadataBundleFromDisk
    metadataBundle.read()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\music21\metadata\bundles.py", line 1152, in read
    raise MetadataBundleException('Cannot load file ' + str(filePath)) from e
music21.metadata.bundles.MetadataBundleException: Cannot load file C:\Users\PC\AppData\Local\Programs\Python\Python37\Lib\site-packages\music21\corpus\_metadataCache\core.p.gz`

Thank you :)

**Comment by NadiaCarvalho** [comment]
Same error in Python 3.7.6 and 3.8.1 in windows 10, while calling corpus.corpora.CoreCorpus().all().

music21 version: 5.7.2

Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\music21\metadata\bundles.py", line 1147, in read
    newMdb = pickle.loads(uncompressed)
  File "C:\Python\Python37\lib\pathlib.py", line 1025, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
PS D:\FEUP_1920\DISS\Dissertation\system> py -3.7 main.py
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\music21\metadata\bundles.py", line 1147, in read
    newMdb = pickle.loads(uncompressed)
  File "C:\Python\Python37\lib\pathlib.py", line 1025, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    metadata = corpus.corpora.CoreCorpus().all()
  File "C:\Python\Python37\lib\site-packages\music21\corpus\corpora.py", line 425, in all    
    return self.metadataBundle
  File "C:\Python\Python37\lib\site-packages\music21\corpus\corpora.py", line 412, in metadataBundle
    mdb = manager.getMetadataBundleByCorpus(self)
  File "C:\Python\Python37\lib\site-packages\music21\corpus\manager.py", line 304, in getMetadataBundleByCorpus
    cacheMetadataBundleFromDisk(corpusObject)
  File "C:\Python\Python37\lib\site-packages\music21\corpus\manager.py", line 320, in cacheMetadataBundleFromDisk
    metadataBundle.read()
  File "C:\Python\Python37\lib\site-packages\music21\metadata\bundles.py", line 1152, in read
    raise MetadataBundleException('Cannot load file ' + str(filePath)) from e
music21.metadata.bundles.MetadataBundleException: Cannot load file C:\Python\Python37\Lib\site-packages\music21\corpus\_metadataCache\core.p.gz

**Comment by mscuthbert** [comment]
Please confirm you are on the latest music21 version?

**Comment by NadiaCarvalho** [comment]
Yes, I'm in version: 5.7.2: c:\python\python37\lib\site-packages (5.7.2)

**Comment by dioxrichard** [comment]
I currently have the same issue as @NadiaCarvalho and @sebaspm24. I am running on Python version 3.7.6 and music21 version 5.7.6.

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\music21\metadata\bundles.py", line 1147, in read
    newMdb = pickle.loads(uncompressed)
  File "C:\Python37\lib\pathlib.py", line 1025, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\cotto\Desktop\music 21\corpussearching.py", line 6, in <module>
    coreBundle = corpus.corpora.CoreCorpus().all()
  File "C:\Python37\lib\site-packages\music21\corpus\corpora.py", line 425, in all
    return self.metadataBundle
  File "C:\Python37\lib\site-packages\music21\corpus\corpora.py", line 412, in metadataBundle
    mdb = manager.getMetadataBundleByCorpus(self)
  File "C:\Python37\lib\site-packages\music21\corpus\manager.py", line 304, in getMetadataBundleByCorpus
    cacheMetadataBundleFromDisk(corpusObject)
  File "C:\Python37\lib\site-packages\music21\corpus\manager.py", line 320, in cacheMetadataBundleFromDisk
    metadataBundle.read()
  File "C:\Python37\lib\site-packages\music21\metadata\bundles.py", line 1152, in read
    raise MetadataBundleException('Cannot load file ' + str(filePath)) from e
music21.metadata.bundles.MetadataBundleException: Cannot load file C:\Python37\Lib\site-packages\music21\corpus\_metadataCache\core.p.gz

**Comment by sebaspm24** [comment]
I found the solution a pair months ago. Sorry about my englisch but it schould be like that:
#In the file "...Python\Python37\Lib\pathlib.py" you have to change the thefinition of the  "new" function. You will find it mor or less on the line 998. Delete its lines and write like that:

def __new__(cls, *args, **kwargs):
        if cls is Path:
            cls = WindowsPath
        self = cls._from_parts(args, init=False)
        self._init()
        return self


I hope, it can help

**Comment by mscuthbert** [comment]
By "the latest music21 version" I mean the version here on Git, v6.0.5 or something like that.  This has been fixed in the next version, unreleased,

**Comment by KyleQuarles** [comment]
Hi Prof. Cuthbert, I installed the latest version of music21 from Git, but still get this same error on windows 10 with python 3.8.2 using IDLE when running the following command:

chorales = music21.corpus.search('bach', fileExtensions='xml')

Thoughts?

**Comment by mscuthbert** [comment]
Thanks Kyle -- will investigate more now that there's a confirmation.  Will need to rebuild the metadata caches.

**Pull request merged**
