### PR TITLE
Automatic key analysis: correct Krumhansl-Schmuckler tone profile

### PR DESCRIPTION
**Pull request by mjwalter**
Typo correction: the value for C-sharp should be 2.23, not 2.33.

### CODE REVIEW

**Comment by mscuthbert** [comment]
Please fix failing tests caused by the commit.  Can you point me to the original ref. as well.  Thanks!

**Comment by mscuthbert** [comment]
Pinging @mjwalter again.  Thanks!

**Comment by mjwalter** [comment]
Hi @mscuthbert – sorry that I haven't been able to get to this yet. I have a couple of project deadlines coming up but will look into it again by December!

**Comment by mjwalter** [comment]
It appears that the 1982 paper didn't give a table of the actual numbers. Nevertheless, all the sources I can find that cite the Krumhansl–Kessler tone profile give 2.23 as the number for C# – see _[Temperley, The cognition of basic musical structures 173-174](https://books.google.com/books?id=IDoLEvTQuewC&pg=PA173&lpg=PA173&dq=krumhansl+kessler+%226.35+2.23%22&source=bl&ots=wL6ap2tsAU&sig=ACfU3U3gI47j_thL3Hi6U3GjokXxMlLuVQ&hl=en&ppis=_e&sa=X&ved=2ahUKEwjIpJW2zNHmAhVQvFkKHViFBgMQ6AEwAHoECAgQAQ#v=onepage&q&f=false)_; Krumhansl in _[Cognitive Foundations of Musical Pitch](https://books.google.com/books?id=J4dJCAAAQBAJ&pg=PT92&lpg=PT92&dq=krumhansl+kessler+%226.35+2.23%22&source=bl&ots=PFbaWC31yj&sig=ACfU3U0wQaqpxwucgU1e5VmobvpbR57ang&hl=en&ppis=_e&sa=X&ved=2ahUKEwjIpJW2zNHmAhVQvFkKHViFBgMQ6AEwAXoECAoQAQ#v=onepage&q=krumhansl%20kessler%20%226.35%202.23%22&f=false)_; and Krumhansl and Toiviainen, [Dynamics of tonality induction](https://www.escom.org/proceedings/ICMPC2000/Wed/Krumhans.htm), among others. A Google search for `krumhansl kessler "6.35 2.33"` returns only the music21 codebase.

Working on the tests now.

**Comment by mjwalter** [comment]
Updated pull request with fixed tests. Merry Christmas!

**Comment by mscuthbert** [comment]
THANKS!  Wonderful to get the citations.  Merry Christmas to you too!

**Comment by mscuthbert** [comment]
Looking at this again -- it appears that this number was deliberate -- that the only difference between music21's KrumhanslSchmuckler  and KrumhanslKessler weights was this number.  But I cannot find where it comes from at this point (The Krumhansl/Schmuckler Petroushka chord Music Perception article does not have it).  So I'm tempted to make the two synonyms for each other.

**Pull request merged**
