### PR TITLE
Synchronize Measure IDs on Musicxml out

### PR DESCRIPTION
**Pull request by rigaux**
Adding IDs to measures in MusicXML files. I added a call to _synchronizeIds(), just as it works already for other elements (eg, notes).

### CODE REVIEW

**Comment by mscuthbert** [comment]
Can you explain what this change does and add a test to show what the changed output is.  THanks!

(Also a small flake issue)

**Comment by mscuthbert** [comment]
Pinging @rigaux

**Comment by rigaux** [comment]
Sorry for the late update. So: the goal is to export measure IDs to MusicXML. Our group annotates music score, and we need to refer to measures.

At the end, a measure element features an id attribute, e.g., <measure id="m1" number="1">

I also added a test 'testExportIdOfMeasure ' in musicxml/test_m21ToXxml.py. It checks the existence of the 'id' attribute.

**Comment by mscuthbert** [comment]
just fixed the flakes myself.  Will merge if passes.

**Pull request merged**
