### PR TITLE
Fix for issue #1408 (ever-increasing voice numbers in multistaff scor…

### PR DESCRIPTION
**Pull request by gregchapman-dev**
…es with multi-voice staves).

### CODE REVIEW

**Comment by gregchapman-dev** [comment]
I could use some help figuring out how to get `testVoiceNumberOffsetsThreeStaffsInGroup` (in test_m21ToXml.py) to actually test this case.  It doesn't, because the voices get removed by `makeNotation`.

**Comment by gregchapman-dev** [comment]
Figured it out: getET(makeNotation=False) is my friend.  The new test fails without this PR, and succeeds with it.

**Comment by gregchapman-dev** [comment]
You will want to take this ASAP, I think.

**Review by mscuthbert — APPROVED** [review]
THANKS!

**Comment by mscuthbert** [comment]
Thanks for quick fix!

**Pull request merged**
