### PR TITLE
musicxml mid-measure clefs

### PR DESCRIPTION
**Pull request by fzalkow**
Hi,
I solved the issue #28 for the case where I needed it. I don't know if it solves the problem in all respects (I don't know enough about the music21 internals for that), but for my cases it works.
Hope this helps.
Best,
Frank

### CODE REVIEW

**Comment by mscuthbert** [comment]
Can you add a test case to the tests that shows how this works? It looks good to me but I don't want to include code without a test.

**Comment by fzalkow** [comment]
Hi. So far I did only m21 to mx mid-measure clefs. Now I also added mx 2 m21 mid-measure clefs and a test file.

**Comment by fzalkow** [comment]
Added the tests. Seems to work with multiple staves! :)

**Comment by mscuthbert** [comment]
Looks good...going with the merge.  Thank you very much for contributing!

**Pull request merged**
