### PR TITLE
MusicXML chord symbol compatibilty

### PR DESCRIPTION
**Pull request by doctor-schmidt**
Music21's MusicXML output of chord symbols with a flat or sharp is not read
properly by MuseScore 2 and William Vree’s xml2abc.py (Finale works OK).
But this could be fixed by changing the MusicXML tag from a float to an
integer.

### CODE REVIEW

**Comment by mscuthbert** [comment]
Thanks for the note and fix. I can't merge because this simple change has almost 5,000 lines of changed content from the current version. Please make a minimal pull request and resubmit. Thanks!

**Comment by doctor-schmidt** [comment]
Sorry, this is my very first contact with GitHub and Eclipse, so there's a lot of trial and error going on and much to learn. But I’m getting the gist of how things work and will resubmit a minimal pull request.

Happy I got this far and looking forward to contributing to music21 !

Norman

**Comment by mscuthbert** [comment]
Thanks Norman. Let me know if the learning experience turns to real frustration in which case I'll happily take over. Just back from a vacation so I'll look at what the problem might be tomorrow. Thanks for contributing! M

**Comment by doctor-schmidt** [comment]
Having a great learning experience, lots of fun! Hmm, you work during weekends? You must love this stuff.

Appreciate your efforts.

Norman

**Comment by mscuthbert** [comment]
Definitely.  Work almost all times! 

Closing this and moving to #182 instead. :-)

**Pull request closed without merging**
