### PR TITLE
Metronom: fixed fontStyle attribute

### PR DESCRIPTION
**Pull request by marian-schulz**
A small fix to an error I stumbled across. 
The value 'bold' does not belong to fontStyle but to fontWeight.

MusicXml don't accept font-style="bold"

### CODE REVIEW

**Comment by marian-schulz** [comment]
I took a look at the style module and realised that something was not implemented quite right there either. 

Bold is definitely a fontWeight and if that is set as a style, there is trouble with musicXML. 

But the style module says that it allows bold as a style and not only that it even knows 'bolditalic' a hybrid of fontWeight and fontStyle.

I did a second commit here to adress this issue.

I have created a second commit that I think solves the problem elegantly by setting 'bold' as style internally fontWeight and for 'bolditalic' the fontStyle 'italic' and the fontWeight 'bold'.

The alternative would be to adjust the music21ToXML and set the values there as musicXML likes it or to remove 'bold' as style and do without 'bolditalic' altogether.

I think my solution creates the least friction.
Agree ? 


Translated with www.DeepL.com/Translator (free version)

**Comment by marian-schulz** [comment]
In a 3th commit i adapted the doc test in music21ToXml for the MetronomeMark.

**Comment by marian-schulz** [comment]
sorry, did forget to update my master to music21/master

**Comment by mscuthbert** [comment]
Music21 calls both bold and italic fontStyle not font-weight.  In this way it fits more with software like MS Word / Google Docs than like CSS/MusicXML.

**Review by mscuthbert — CHANGES_REQUESTED** [review]
Music21 calls both bold and italic fontStyle not font-weight.  In this way it fits more with software like MS Word / Google Docs than like CSS/MusicXML.

Will accept a change to fix bug in output to MusicXML, not a change to music21's internal model.

**Comment by marian-schulz** [comment]
I close this pull request.
I will did a new one, fixing the problem in the xml export

**Pull request closed without merging**
