### PR TITLE
Fix duplicate id problem.

### PR DESCRIPTION
**Pull request by twcook**
Apologies for the spaces issue at the end of lines.  I have WingIDE set to strip those but apparently it isn't working. 

The changes are base.py 
lines; 45, 400 

stream/core.py
lines; 280, 289 & 290.

### CODE REVIEW

**Comment by ahankinson** [comment]
I rather meant that you *were* stripping the spaces at the ends of lines, which makes it difficult to actually discover the changes. In general, while stripping whitespace and formatting can be good things to do, they typically go under separate commits since they don't affect functionality.

**Comment by twcook** [comment]
Looks like Travis CI is failing on that last update to 
music21/alpha/theoryAnalysis/theoryAnalyzer.py", line 1539

This isn't one of my changes.

**Comment by mscuthbert** [comment]
Sorry, but I can't use time.time() as a way of making a GUID -- many systems only report millisecond or even second accuracy, which means that in a multiprocessor environment, it is very likely that two objects could be created:

```
*time.time()*
Return the time in seconds since the epoch as a floating point number. 
Note that even though the time is always returned as a floating point number, 
not all systems provide time with a better precision than 1 second. 
While this function normally returns non-decreasing values, 
it can return a lower value than a previous call if the system clock has been 
set back between the two calls.
```

You sent me access to files that were going to show why this part of music21 wasn't working for you but nothing in those files uses music21.

Thanks.
M

**Comment by mscuthbert** [comment]
There are a few tests that are broken in the latest Travis-CI build because of something I introduced (was massively interrupted this afternoon, figured no one was using four-part-multi-staff braille, so breaking a test that wasn't working in the first place would not be a big deal...), but the vast majority of the broken tests here are all from this patch.  Including everything in theoryAnalysis.

**Comment by twcook** [comment]
You sent me access to files that were going to show why this part of music21 wasn't working for you but nothing in those files uses music21.

Did you try the music21_based branch as I suggested?

Thanks for the open source code.  Some of it will be useful.  But as a whole the fundamental approach of using python object ids as a unique ID is a bad idea.  I can't think of a modern POSIX compliant/compatible system that the time.time() warning applies to anymore. I am certain you won't find a multiprocessor environment running an OS that doesn't report microsecond accuracy.  Think about it.

**Comment by mscuthbert** [comment]
ah, I didn't see that there was a separate branch -- will check.

**Comment by mscuthbert** [comment]
I had a chance to look at the Stream.core() change and I don't think it'll solve whatever problem is arising for you.  The id(el) check is just a fast way of saying, "does the stream THINK it might have the element in it already?" and only if that returns yes, do we actually do a slow, iterative "IS" search checking whether the element is in the stream.  I suspect that the problem, if any, should be elsewhere. Thanks!

**Pull request closed without merging**
