### PR TITLE
Significantly improve performance of midi file loading.

### PR DESCRIPTION
**Pull request by HalfVoxel**
This was done primarily by removing some cases were extremely inefficient quadratic algorithms were used where a simpler linear (or at least linear for all reasonable midi files which don't have all notes in the same location) algorithm would work.

There are still several cases were quadratic algorithms are still used and they definitely should be optimized.

In my tests this made midi file loading approximately 5.5x faster.

### CODE REVIEW

**Comment by mscuthbert** [comment]
Coverage decrease is acceptable since it comes only from reducing the length of well-tested code.

**Comment by mscuthbert** [comment]
Merging.  Would love to have more places where quadratic speedups can be introduced.  One major culprit remaining is in the parsing of multi-staff (piano for instance) parts in musicxml.

**Comment by HalfVoxel** [comment]
A good candidate for optimization is the deep copy methods. They are currently quadratic because the purgeOrphans method (which is called for every note) usually has to look through all elements in the stream that is being deep copied.

**Comment by mscuthbert** [comment]
ah! I think that there was a planned item to improve purgeOrphans at some point a long time ago -- I'm not sure if we timed it in real life cases and figured it wasn't a problem, or just never got around to it.

**Comment by mscuthbert** [comment]
(Sorry thought it was already merged!)

**Pull request merged**
